-- Stellar Diary V0.19.1 — Pet system 1.0 / #7001 牙牙
-- Run AFTER 20260928_031_friend_avatar_visuals.sql.
-- Adds a permanent pet inventory, active follower state, GM mail delivery,
-- and a strictly whitelisted public active-pet field for friend farm visits.

begin;

alter table public.mail_item_catalog
  drop constraint if exists mail_item_catalog_category_check,
  drop constraint if exists mail_item_catalog_reward_kind_check,
  drop constraint if exists mail_item_catalog_state_key_check,
  drop constraint if exists mail_item_catalog_icon_source_check;

-- Older databases can carry an autogenerated icon_source CHECK name.
do $$
declare r record;
begin
  for r in
    select conname from pg_constraint
     where conrelid='public.mail_item_catalog'::regclass
       and contype='c'
       and pg_get_constraintdef(oid) ilike '%icon_source%'
  loop
    execute format('alter table public.mail_item_catalog drop constraint %I', r.conname);
  end loop;
end $$;

alter table public.mail_item_catalog
  add constraint mail_item_catalog_category_check
    check (category in ('currency','box','seed','supply','outfit','decoration','pet')),
  add constraint mail_item_catalog_reward_kind_check
    check (reward_kind in ('coin','exp','seed','supply','outfit','decoration','pet')),
  add constraint mail_item_catalog_state_key_check check (
    (reward_kind in ('coin','exp') and state_key is null)
    or (reward_kind in ('seed','supply','outfit','decoration','pet') and nullif(state_key,'') is not null)
  ),
  add constraint mail_item_catalog_icon_source_check
    check (icon_source in ('farm','farm_item','farm_catalog','farm_pet','site'));

insert into public.mail_item_catalog
(item_id,item_code,category,reward_kind,state_key,name_zh_cn,name_zh_tw,name_en,icon_source,icon_key,icon_cell,max_quantity,sort_order,mail_enabled,active)
values
(7001,'pet.ya_ya','pet','pet','ya_ya','牙牙','牙牙','Yaya','farm_pet','ya_ya',null,1,501,true,true)
on conflict (item_id) do update set
  item_code=excluded.item_code,
  category=excluded.category,
  reward_kind=excluded.reward_kind,
  state_key=excluded.state_key,
  name_zh_cn=excluded.name_zh_cn,
  name_zh_tw=excluded.name_zh_tw,
  name_en=excluded.name_en,
  icon_source=excluded.icon_source,
  icon_key=excluded.icon_key,
  icon_cell=excluded.icon_cell,
  max_quantity=excluded.max_quantity,
  sort_order=excluded.sort_order,
  mail_enabled=excluded.mail_enabled,
  active=excluded.active,
  updated_at=now();

create or replace function public.claim_system_mail_v1(p_mail_id bigint)
returns table(ok boolean, reason text, rewards jsonb, farm_state jsonb, revision bigint)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_rewards jsonb;
  v_state jsonb;
  v_claimed timestamptz;
  v_key text;
  v_value jsonb;
  v_qty integer;
  v_current integer;
  v_coins integer;
  v_exp integer;
  v_exp_bonus integer := 0;
  v_level integer;
  v_need integer;
  v_revision bigint;
  v_item jsonb;
  v_item_id integer;
  v_kind text;
  v_state_key text;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode='28000'; end if;
  if not exists(select 1 from auth.users u where u.id=v_uid and nullif(u.email,'') is not null) then
    return query select false,'member_required','{}'::jsonb,null::jsonb,null::bigint; return;
  end if;

  if exists(
    select 1 from public.player_mail_state s
     where s.user_id=v_uid and s.mail_id=p_mail_id and s.deleted_at is not null
  ) then
    return query select false,'mail_deleted','{}'::jsonb,null::jsonb,null::bigint; return;
  end if;

  select m.rewards into v_rewards
    from public.system_mail m
   where m.id=p_mail_id and m.starts_at<=now() and (m.expires_at is null or m.expires_at>now())
     and (m.audience_type='all' or (m.audience_type='user' and m.target_user_id=v_uid))
   for share;
  if not found then return query select false,'mail_unavailable','{}'::jsonb,null::jsonb,null::bigint; return; end if;
  perform private.validate_mail_rewards(v_rewards);
  if v_rewards='{}'::jsonb or (v_rewards ? 'items' and jsonb_array_length(v_rewards->'items')=0 and (v_rewards-'items')='{}'::jsonb) then
    return query select false,'no_attachments',v_rewards,null::jsonb,null::bigint; return;
  end if;

  insert into public.player_mail_state(user_id,mail_id,read_at,claimed_at)
  values(v_uid,p_mail_id,now(),null)
  on conflict(user_id,mail_id) do nothing;

  select s.claimed_at into v_claimed
    from public.player_mail_state s where s.user_id=v_uid and s.mail_id=p_mail_id for update;
  if v_claimed is not null then return query select false,'already_claimed',v_rewards,null::jsonb,null::bigint; return; end if;

  insert into public.farm_saves(user_id,state,client_updated_at)
  values(v_uid,jsonb_build_object(
      'version',1,'createdAt',floor(extract(epoch from now())*1000)::bigint,
      'coins',100,'level',1,'exp',0,'plots','[]'::jsonb,
      'seeds',jsonb_build_object('carrot',3,'wheat',2),'produce','{}'::jsonb,
      'supplies',jsonb_build_object('fertilizerLow',0,'fertilizerMid',0,'fertilizerHigh',0,'trainResetTicket',0),
      'decorations',jsonb_build_object('owned','{}'::jsonb,'slots',jsonb_build_array(null,null,null,null,null,null,null,null)),
      'wardrobe',jsonb_build_object('outfits',jsonb_build_object('default',true)),
      'avatar',jsonb_build_object('gender','male','outfit','default'),
      'pets',jsonb_build_object('owned','{}'::jsonb,'active',null),
      'stats',jsonb_build_object('visit',1,'plant',0,'harvest',0,'sell',0,'friend',0,'blindBoxPlant',0,'steals',0,'maxCoins',100),
      'updatedAt',floor(extract(epoch from now())*1000)::bigint),
    floor(extract(epoch from now())*1000)::bigint)
  on conflict(user_id) do nothing;

  select fs.state into v_state from public.farm_saves fs where fs.user_id=v_uid for update;
  v_state := coalesce(v_state,'{}'::jsonb);
  v_state := jsonb_set(v_state,'{seeds}',coalesce(v_state->'seeds','{}'::jsonb),true);
  v_state := jsonb_set(v_state,'{supplies}',coalesce(v_state->'supplies','{}'::jsonb),true);
  v_state := jsonb_set(v_state,'{stats}',coalesce(v_state->'stats','{}'::jsonb),true);
  if coalesce(jsonb_typeof(v_state->'decorations'),'') <> 'object' then
    v_state := jsonb_set(v_state,'{decorations}','{}'::jsonb,true);
  end if;
  if coalesce(jsonb_typeof(v_state->'decorations'->'owned'),'') <> 'object' then
    v_state := jsonb_set(v_state,'{decorations,owned}','{}'::jsonb,true);
  end if;
  if coalesce(jsonb_typeof(v_state->'decorations'->'slots'),'') <> 'array' then
    v_state := jsonb_set(v_state,'{decorations,slots}',jsonb_build_array(null,null,null,null,null,null,null,null),true);
  end if;
  if coalesce(jsonb_typeof(v_state->'wardrobe'),'') <> 'object' then
    v_state := jsonb_set(v_state,'{wardrobe}','{}'::jsonb,true);
  end if;
  if coalesce(jsonb_typeof(v_state->'wardrobe'->'outfits'),'') <> 'object' then
    v_state := jsonb_set(v_state,'{wardrobe,outfits}','{}'::jsonb,true);
  end if;
  v_state := jsonb_set(v_state,'{wardrobe,outfits,default}','true'::jsonb,true);
  if coalesce(jsonb_typeof(v_state->'pets'),'') <> 'object' then
    v_state := jsonb_set(v_state,'{pets}','{}'::jsonb,true);
  end if;
  if coalesce(jsonb_typeof(v_state->'pets'->'owned'),'') <> 'object' then
    v_state := jsonb_set(v_state,'{pets,owned}','{}'::jsonb,true);
  end if;
  if not (v_state->'pets' ? 'active') then
    v_state := jsonb_set(v_state,'{pets,active}','null'::jsonb,true);
  end if;

  v_coins := greatest(0,coalesce(nullif(v_state->>'coins','')::integer,0));
  v_exp_bonus := greatest(0,coalesce((v_rewards->>'exp')::integer,0));

  if v_rewards ? 'items' then
    for v_item in select value from jsonb_array_elements(v_rewards->'items') loop
      v_item_id := (v_item->>'item_id')::integer;
      v_qty := (v_item->>'quantity')::integer;
      select c.reward_kind,c.state_key into v_kind,v_state_key
        from public.mail_item_catalog c
       where c.item_id=v_item_id and c.active and c.mail_enabled;
      if v_kind='coin' then
        v_coins := v_coins + v_qty;
      elsif v_kind='exp' then
        v_exp_bonus := v_exp_bonus + v_qty;
      elsif v_kind='seed' then
        v_current := greatest(0,coalesce(nullif(v_state->'seeds'->>v_state_key,'')::integer,0));
        v_state := jsonb_set(v_state,array['seeds',v_state_key],to_jsonb(v_current+v_qty),true);
      elsif v_kind='supply' then
        v_current := greatest(0,coalesce(nullif(v_state->'supplies'->>v_state_key,'')::integer,0));
        v_state := jsonb_set(v_state,array['supplies',v_state_key],to_jsonb(v_current+v_qty),true);
      elsif v_kind='outfit' then
        v_state := jsonb_set(v_state,array['wardrobe','outfits',v_state_key],'true'::jsonb,true);
      elsif v_kind='decoration' then
        v_current := greatest(0,coalesce(nullif(v_state->'decorations'->'owned'->>v_state_key,'')::integer,0));
        v_state := jsonb_set(v_state,array['decorations','owned',v_state_key],to_jsonb(v_current+v_qty),true);
      elsif v_kind='pet' then
        v_state := jsonb_set(v_state,array['pets','owned',v_state_key],'true'::jsonb,true);
      end if;
    end loop;
  end if;

  -- Legacy V0.16 attachments remain supported.
  v_coins := v_coins + greatest(0,coalesce((v_rewards->>'coins')::integer,0));
  if v_rewards ? 'seeds' then
    for v_key,v_value in select key,value from jsonb_each(v_rewards->'seeds') loop
      v_qty := greatest(0,trim(both '"' from v_value::text)::integer);
      v_current := greatest(0,coalesce(nullif(v_state->'seeds'->>v_key,'')::integer,0));
      v_state := jsonb_set(v_state,array['seeds',v_key],to_jsonb(v_current+v_qty),true);
    end loop;
  end if;
  if v_rewards ? 'supplies' then
    for v_key,v_value in select key,value from jsonb_each(v_rewards->'supplies') loop
      v_qty := greatest(0,trim(both '"' from v_value::text)::integer);
      v_current := greatest(0,coalesce(nullif(v_state->'supplies'->>v_key,'')::integer,0));
      v_state := jsonb_set(v_state,array['supplies',v_key],to_jsonb(v_current+v_qty),true);
    end loop;
  end if;

  v_state := jsonb_set(v_state,'{coins}',to_jsonb(v_coins),true);
  v_current := greatest(v_coins,coalesce(nullif(v_state->'stats'->>'maxCoins','')::integer,0));
  v_state := jsonb_set(v_state,'{stats,maxCoins}',to_jsonb(v_current),true);

  v_level := greatest(1,coalesce(nullif(v_state->>'level','')::integer,1));
  v_exp := greatest(0,coalesce(nullif(v_state->>'exp','')::integer,0)) + v_exp_bonus;
  loop
    v_need := private.farm_exp_need(v_level);
    exit when v_exp < v_need;
    v_exp := v_exp-v_need;
    v_level := v_level+1;
  end loop;
  v_state := jsonb_set(v_state,'{level}',to_jsonb(v_level),true);
  v_state := jsonb_set(v_state,'{exp}',to_jsonb(v_exp),true);
  v_state := jsonb_set(v_state,'{updatedAt}',to_jsonb(floor(extract(epoch from now())*1000)::bigint),true);

  update public.farm_saves fs
     set state=v_state,client_updated_at=floor(extract(epoch from now())*1000)::bigint,updated_at=now()
   where fs.user_id=v_uid
   returning fs.revision into v_revision;

  update public.player_mail_state
     set read_at=coalesce(read_at,now()),claimed_at=now()
   where user_id=v_uid and mail_id=p_mail_id;

  return query select true,'claimed',v_rewards,v_state,v_revision;
end;
$$;

revoke execute on function public.claim_system_mail_v1(bigint) from public,anon,authenticated;

create or replace function public.get_friend_farm_v5(
  p_friend uuid,
  p_log_visit boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_payload jsonb;
  v_state jsonb;
  v_slots jsonb := '[]'::jsonb;
  v_outfit text := 'default';
  v_pet text := null;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  end if;

  -- Reuse V4 for friendship validation, public profile, plots and visit logging.
  v_payload := public.get_friend_farm_v4(p_friend, p_log_visit);
  if not coalesce((v_payload->>'ok')::boolean, false) then
    return v_payload;
  end if;

  select fs.state into v_state
    from public.farm_saves fs
   where fs.user_id = p_friend;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'no_farm');
  end if;

  -- Keep the public farm view strictly whitelisted. Only valid scene decoration
  -- ids are returned; inventory counts and unpublished save fields stay private.
  select coalesce(jsonb_agg(
    case
      when (v_state #>> array['decorations','slots',g.i::text]) in
        ('hay','barrels','flowerbed','wheel','birdhouse','bench','scarecrow','lamp','windmill','sign',
         'mid_lantern','mid_rabbit','mid_osmanthus','mid_moon_lamp',
         'halloween_pumpkin','halloween_ghost','halloween_candle',
         'christmas_tree','christmas_gifts','christmas_snowman','christmas_lamp')
      then to_jsonb(v_state #>> array['decorations','slots',g.i::text])
      else 'null'::jsonb
    end order by g.i
  ), '[]'::jsonb)
  into v_slots
  from generate_series(0,7) as g(i);

  v_outfit := case
    when coalesce(v_state #>> '{avatar,outfit}','default') in ('default','mid_autumn','halloween','christmas')
      then coalesce(v_state #>> '{avatar,outfit}','default')
    else 'default'
  end;

  v_pet := case
    when coalesce(v_state #>> '{pets,active}','') in ('ya_ya')
      and coalesce((v_state #>> '{pets,owned,ya_ya}')::boolean,false)
      then v_state #>> '{pets,active}'
    else null
  end;

  return v_payload || jsonb_build_object(
    'avatar', jsonb_build_object('outfit', v_outfit),
    'pet', jsonb_build_object('active', v_pet),
    'decorations', jsonb_build_object('slots', v_slots)
  );
end;
$$;

revoke all on function public.get_friend_farm_v5(uuid,boolean) from public, anon;
grant execute on function public.get_friend_farm_v5(uuid,boolean) to authenticated, service_role;

commit;
