-- Stellar Diary V0.13.4 — friend crop stealing + visit metadata
-- Run once after migration 005. Stealing is server-validated and atomic.
-- Rules: accepted friends only; mature crops only; same friend once per growth cycle;
-- steal 1–3 at random while the owner always keeps at least 1.

begin;

create table if not exists public.farm_steals (
  id bigint generated by default as identity primary key,
  thief_id uuid not null references auth.users(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  plot_id integer not null check (plot_id between 0 and 19),
  planted_at bigint not null check (planted_at > 0),
  crop_id text not null check (crop_id in ('carrot','wheat','corn','tomato','strawberry','pumpkin','grape','starfruit')),
  amount integer not null check (amount between 1 and 3),
  created_at timestamptz not null default now(),
  constraint farm_steals_distinct_users check (thief_id <> owner_id),
  constraint farm_steals_once_per_friend_cycle unique (thief_id, owner_id, plot_id, planted_at)
);

create index if not exists idx_farm_steals_owner_plot_cycle
  on public.farm_steals(owner_id, plot_id, planted_at);
create index if not exists idx_farm_steals_thief_created
  on public.farm_steals(thief_id, created_at desc);

alter table public.farm_steals enable row level security;
revoke all on table public.farm_steals from public, anon, authenticated;
grant all privileges on table public.farm_steals to service_role;

-- Replace the visit payload so the UI can show stealable mature plots without
-- exposing the owner's inventory, tasks or full private save.
create or replace function public.get_friend_farm(p_friend uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_state jsonb;
  v_updated_at timestamptz;
  v_display_name text;
  v_sex text;
  v_level integer := 1;
  v_coins bigint := 0;
  v_plots jsonb := '[]'::jsonb;
  v_low uuid;
  v_high uuid;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  end if;
  if p_friend is null or p_friend = v_uid then
    return jsonb_build_object('ok', false, 'reason', 'invalid_target');
  end if;

  if v_uid::text < p_friend::text then v_low := v_uid; v_high := p_friend;
  else v_low := p_friend; v_high := v_uid; end if;

  if not exists (
    select 1 from public.farm_friendships f
    where f.user_low = v_low and f.user_high = v_high and f.status = 'accepted'
  ) then
    return jsonb_build_object('ok', false, 'reason', 'not_friend');
  end if;

  select fs.state, fs.updated_at,
         coalesce(nullif(trim(p.display_name), ''), '星辰农友'),
         case when p.sex in ('male','female') then p.sex else 'unspecified' end
  into v_state, v_updated_at, v_display_name, v_sex
  from public.farm_saves fs
  join public.profiles p on p.id = fs.user_id
  where fs.user_id = p_friend;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'no_farm');
  end if;

  v_level := least(999, greatest(1,
    case when coalesce(v_state->>'level','') ~ '^[0-9]+$'
      then (v_state->>'level')::integer else 1 end));
  v_coins := least(999999999999::bigint, greatest(0::bigint,
    case when coalesce(v_state->>'coins','') ~ '^[0-9]+$'
      then (v_state->>'coins')::bigint else 0::bigint end));

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'id', (plot.ord - 1)::integer,
      'cropId', case
        when plot.elem->>'cropId' in ('carrot','wheat','corn','tomato','strawberry','pumpkin','grape','starfruit','mystery')
          then plot.elem->>'cropId' else null end,
      'plantedAt', case
        when coalesce(plot.elem->>'plantedAt','') ~ '^[0-9]+$'
          then (plot.elem->>'plantedAt')::bigint else null end,
      'resultCropId', case
        when plot.elem->>'resultCropId' in ('carrot','wheat','corn','tomato','strawberry','pumpkin','grape','starfruit')
          then plot.elem->>'resultCropId' else null end,
      'harvestYield', case
        when coalesce(plot.elem->>'harvestYield','') ~ '^[0-9]+$'
          then least(5, greatest(1, (plot.elem->>'harvestYield')::integer)) else null end,
      'stolenCount', case
        when coalesce(plot.elem->>'stolenCount','') ~ '^[0-9]+$'
          then least(4, greatest(0, (plot.elem->>'stolenCount')::integer)) else 0 end,
      'stolenByMe', exists (
        select 1 from public.farm_steals st
        where st.thief_id = v_uid
          and st.owner_id = p_friend
          and st.plot_id = (plot.ord - 1)::integer
          and st.planted_at = case
            when coalesce(plot.elem->>'plantedAt','') ~ '^[0-9]+$'
              then (plot.elem->>'plantedAt')::bigint else -1 end
      )
    ) order by plot.ord
  ), '[]'::jsonb)
  into v_plots
  from jsonb_array_elements(coalesce(v_state->'plots', '[]'::jsonb)) with ordinality as plot(elem, ord)
  where plot.ord <= 20;

  return jsonb_build_object(
    'ok', true, 'user_id', p_friend, 'display_name', v_display_name, 'sex', v_sex,
    'level', v_level, 'coins', v_coins, 'plots', v_plots, 'updated_at', v_updated_at
  );
end;
$$;

create or replace function public.steal_friend_crop(p_friend uuid, p_plot integer)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_low uuid;
  v_high uuid;
  v_owner_state jsonb;
  v_thief_state jsonb;
  v_plot jsonb;
  v_crop_id text;
  v_planted_at bigint;
  v_grow_minutes integer;
  v_now_ms bigint := floor(extract(epoch from clock_timestamp()) * 1000)::bigint;
  v_total integer;
  v_stolen integer := 0;
  v_remaining integer;
  v_max_take integer;
  v_take integer;
  v_current_produce integer := 0;
begin
  if v_uid is null then return jsonb_build_object('ok', false, 'reason', 'not_authenticated'); end if;
  if p_friend is null or p_friend = v_uid or p_plot is null or p_plot < 0 or p_plot > 19 then
    return jsonb_build_object('ok', false, 'reason', 'invalid_target');
  end if;

  if v_uid::text < p_friend::text then v_low := v_uid; v_high := p_friend;
  else v_low := p_friend; v_high := v_uid; end if;

  if not exists (
    select 1 from public.farm_friendships f
    where f.user_low = v_low and f.user_high = v_high and f.status = 'accepted'
  ) then return jsonb_build_object('ok', false, 'reason', 'not_friend'); end if;

  -- Serialize steals against this owner's farm so concurrent visitors cannot
  -- take past the guaranteed final item.
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_friend::text || ':' || p_plot::text, 0));

  select fs.state into v_owner_state
  from public.farm_saves fs where fs.user_id = p_friend for update;
  if not found then return jsonb_build_object('ok', false, 'reason', 'no_farm'); end if;

  select fs.state into v_thief_state
  from public.farm_saves fs where fs.user_id = v_uid for update;
  if not found then return jsonb_build_object('ok', false, 'reason', 'no_own_farm'); end if;

  v_plot := v_owner_state->'plots'->p_plot;
  if v_plot is null then return jsonb_build_object('ok', false, 'reason', 'no_crop'); end if;
  v_crop_id := v_plot->>'cropId';
  if v_crop_id is null or v_crop_id = '' then return jsonb_build_object('ok', false, 'reason', 'no_crop'); end if;
  if v_crop_id = 'mystery' then return jsonb_build_object('ok', false, 'reason', 'protected'); end if;
  if v_crop_id not in ('carrot','wheat','corn','tomato','strawberry','pumpkin','grape','starfruit') then
    return jsonb_build_object('ok', false, 'reason', 'no_crop');
  end if;

  if coalesce(v_plot->>'plantedAt','') !~ '^[0-9]+$' then
    return jsonb_build_object('ok', false, 'reason', 'no_crop');
  end if;
  v_planted_at := (v_plot->>'plantedAt')::bigint;

  v_grow_minutes := case v_crop_id
    when 'carrot' then 20 when 'wheat' then 30 when 'corn' then 30 when 'tomato' then 50
    when 'strawberry' then 90 when 'pumpkin' then 150 when 'grape' then 240 when 'starfruit' then 480
    else 999999 end;
  if v_now_ms - v_planted_at < v_grow_minutes::bigint * 60000 then
    return jsonb_build_object('ok', false, 'reason', 'not_mature');
  end if;

  if exists (
    select 1 from public.farm_steals st
    where st.thief_id = v_uid and st.owner_id = p_friend and st.plot_id = p_plot and st.planted_at = v_planted_at
  ) then return jsonb_build_object('ok', false, 'reason', 'already_stolen'); end if;

  if coalesce(v_plot->>'harvestYield','') ~ '^[0-9]+$' then
    v_total := least(5, greatest(4, (v_plot->>'harvestYield')::integer));
  else
    v_total := 4 + floor(random() * 2)::integer;
  end if;

  select coalesce(sum(st.amount), 0)::integer into v_stolen
  from public.farm_steals st
  where st.owner_id = p_friend and st.plot_id = p_plot and st.planted_at = v_planted_at;

  v_remaining := v_total - v_stolen;
  if v_remaining <= 1 then return jsonb_build_object('ok', false, 'reason', 'protected', 'remaining', 1); end if;

  v_max_take := least(3, v_remaining - 1);
  v_take := 1 + floor(random() * v_max_take)::integer;

  insert into public.farm_steals(thief_id, owner_id, plot_id, planted_at, crop_id, amount)
  values(v_uid, p_friend, p_plot, v_planted_at, v_crop_id, v_take);
  v_stolen := v_stolen + v_take;
  v_remaining := v_total - v_stolen;

  -- Persist the authoritative yield/steal counters into the owner's sanitized
  -- plot state so their next cloud pull immediately reflects the loss.
  v_owner_state := jsonb_set(v_owner_state, array['plots', p_plot::text, 'harvestYield'], to_jsonb(v_total), true);
  v_owner_state := jsonb_set(v_owner_state, array['plots', p_plot::text, 'stolenCount'], to_jsonb(v_stolen), true);
  v_owner_state := jsonb_set(v_owner_state, '{updatedAt}', to_jsonb(v_now_ms), true);

  v_thief_state := jsonb_set(v_thief_state, '{produce}', coalesce(v_thief_state->'produce', '{}'::jsonb), true);
  if coalesce(v_thief_state->'produce'->>v_crop_id,'') ~ '^[0-9]+$' then
    v_current_produce := (v_thief_state->'produce'->>v_crop_id)::integer;
  end if;
  v_thief_state := jsonb_set(v_thief_state, array['produce', v_crop_id], to_jsonb(v_current_produce + v_take), true);
  v_thief_state := jsonb_set(v_thief_state, '{updatedAt}', to_jsonb(v_now_ms), true);

  update public.farm_saves
    set state = v_owner_state, client_updated_at = v_now_ms
    where user_id = p_friend;
  update public.farm_saves
    set state = v_thief_state, client_updated_at = v_now_ms
    where user_id = v_uid;

  return jsonb_build_object(
    'ok', true,
    'crop_id', v_crop_id,
    'amount', v_take,
    'owner_remaining', v_remaining,
    'thief_state', v_thief_state
  );
end;
$$;

revoke all on function public.get_friend_farm(uuid) from public, anon;
revoke all on function public.steal_friend_crop(uuid,integer) from public, anon;
grant execute on function public.get_friend_farm(uuid) to authenticated, service_role;
grant execute on function public.steal_friend_crop(uuid,integer) to authenticated, service_role;

commit;
