-- Stellar Diary V0.16.1 — GM roles + system mailbox + atomic reward claiming
-- Run ONCE in Supabase SQL Editor after the existing farm migrations.
-- First GM is bootstrapped by immutable Auth UUID, not by email.

begin;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'gm' check (role in ('super_admin','gm','support')),
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.system_mail (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  body text not null default '' check (char_length(body) <= 6000),
  mail_type text not null default 'announcement' check (mail_type in ('announcement','reward')),
  audience_type text not null default 'all' check (audience_type in ('all','user')),
  target_user_id uuid references auth.users(id) on delete cascade,
  rewards jsonb not null default '{}'::jsonb check (jsonb_typeof(rewards) = 'object'),
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint system_mail_target_check check (
    (audience_type = 'all' and target_user_id is null)
    or (audience_type = 'user' and target_user_id is not null)
  ),
  constraint system_mail_expiry_check check (expires_at is null or expires_at > starts_at)
);

create index if not exists system_mail_active_idx on public.system_mail(starts_at desc, expires_at);
create index if not exists system_mail_target_idx on public.system_mail(target_user_id, starts_at desc);

create table if not exists public.player_mail_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  mail_id bigint not null references public.system_mail(id) on delete cascade,
  read_at timestamptz,
  claimed_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (user_id, mail_id)
);

create index if not exists player_mail_state_user_idx on public.player_mail_state(user_id, read_at, claimed_at);

create table if not exists public.gm_audit_log (
  id bigint generated by default as identity primary key,
  gm_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  subject_id text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists gm_audit_log_created_idx on public.gm_audit_log(created_at desc);

alter table public.admin_users enable row level security;
alter table public.system_mail enable row level security;
alter table public.player_mail_state enable row level security;
alter table public.gm_audit_log enable row level security;

revoke all on table public.admin_users from public, anon, authenticated;
revoke all on table public.system_mail from public, anon, authenticated;
revoke all on table public.player_mail_state from public, anon, authenticated;
revoke all on table public.gm_audit_log from public, anon, authenticated;

-- The first account selected by the site owner is the only initial super admin.
insert into public.admin_users(user_id, role, display_name)
values ('e6eb4bcd-4e0f-43cb-ba02-44161794ac27'::uuid, 'super_admin', 'Stellar Diary GM')
on conflict (user_id) do update set role = excluded.role, display_name = excluded.display_name;

create or replace function private.is_stellar_gm(p_uid uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1 from public.admin_users a
    where a.user_id = p_uid and a.role in ('super_admin','gm')
  );
$$;

create or replace function private.farm_exp_need(p_level integer)
returns integer
language sql
immutable
set search_path = ''
as $$
  select case p_level
    when 1 then 100 when 2 then 140 when 3 then 190 when 4 then 250 when 5 then 320
    when 6 then 400 when 7 then 500 when 8 then 620 when 9 then 750 when 10 then 900
    when 11 then 1060 when 12 then 1230 when 13 then 1410 when 14 then 1600 when 15 then 1800
    when 16 then 2010 when 17 then 2230 when 18 then 2460 when 19 then 2700 when 20 then 2950
    when 21 then 3210 when 22 then 3480 when 23 then 3760 when 24 then 4050 when 25 then 4350
    else 4350 + greatest(0, p_level - 25) * 350
  end;
$$;

create or replace function private.validate_mail_rewards(p_rewards jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_key text;
  v_value jsonb;
  v_num numeric;
begin
  if p_rewards is null or jsonb_typeof(p_rewards) <> 'object' then
    raise exception 'invalid_rewards' using errcode='22023';
  end if;

  if (p_rewards - 'coins' - 'exp' - 'seeds' - 'supplies') <> '{}'::jsonb then
    raise exception 'unknown_reward_key' using errcode='22023';
  end if;

  foreach v_key in array array['coins','exp'] loop
    if p_rewards ? v_key then
      begin v_num := (p_rewards->>v_key)::numeric; exception when others then raise exception 'invalid_reward_quantity'; end;
      if v_num < 0 or v_num > 1000000 or trunc(v_num) <> v_num then raise exception 'invalid_reward_quantity'; end if;
    end if;
  end loop;

  if p_rewards ? 'seeds' then
    if jsonb_typeof(p_rewards->'seeds') <> 'object' then raise exception 'invalid_seed_rewards'; end if;
    for v_key, v_value in select key, value from jsonb_each(p_rewards->'seeds') loop
      if v_key not in ('carrot','wheat','corn','tomato','strawberry','pumpkin','grape','starfruit','mystery') then
        raise exception 'unknown_seed_reward';
      end if;
      begin v_num := trim(both '"' from v_value::text)::numeric; exception when others then raise exception 'invalid_reward_quantity'; end;
      if v_num < 0 or v_num > 100000 or trunc(v_num) <> v_num then raise exception 'invalid_reward_quantity'; end if;
    end loop;
  end if;

  if p_rewards ? 'supplies' then
    if jsonb_typeof(p_rewards->'supplies') <> 'object' then raise exception 'invalid_supply_rewards'; end if;
    for v_key, v_value in select key, value from jsonb_each(p_rewards->'supplies') loop
      if v_key not in ('fertilizerLow','fertilizerMid','fertilizerHigh') then raise exception 'unknown_supply_reward'; end if;
      begin v_num := trim(both '"' from v_value::text)::numeric; exception when others then raise exception 'invalid_reward_quantity'; end;
      if v_num < 0 or v_num > 100000 or trunc(v_num) <> v_num then raise exception 'invalid_reward_quantity'; end if;
    end loop;
  end if;
end;
$$;

create or replace function public.is_gm_v1()
returns table(is_gm boolean, role text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    return query select false, null::text;
    return;
  end if;
  return query
    select true, a.role from public.admin_users a where a.user_id = v_uid and a.role in ('super_admin','gm')
    union all
    select false, null::text where not exists(select 1 from public.admin_users a2 where a2.user_id = v_uid and a2.role in ('super_admin','gm'))
    limit 1;
end;
$$;

create or replace function public.get_mailbox_v1(p_limit integer default 60)
returns table(
  id bigint,
  title text,
  body text,
  mail_type text,
  rewards jsonb,
  starts_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz,
  read_at timestamptz,
  claimed_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode='28000'; end if;
  return query
    select m.id, m.title, m.body, m.mail_type, m.rewards, m.starts_at, m.expires_at, m.created_at,
           s.read_at, s.claimed_at
      from public.system_mail m
      left join public.player_mail_state s on s.user_id = v_uid and s.mail_id = m.id
     where m.starts_at <= now()
       and (m.expires_at is null or m.expires_at > now())
       and (m.audience_type = 'all' or (m.audience_type = 'user' and m.target_user_id = v_uid))
     order by m.created_at desc, m.id desc
     limit least(greatest(coalesce(p_limit,60),1),100);
end;
$$;

create or replace function public.get_mailbox_unread_v1()
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select case when auth.uid() is null then 0 else (
    select count(*)::integer
    from public.system_mail m
    left join public.player_mail_state s on s.user_id = auth.uid() and s.mail_id = m.id
    where m.starts_at <= now()
      and (m.expires_at is null or m.expires_at > now())
      and (m.audience_type = 'all' or (m.audience_type = 'user' and m.target_user_id = auth.uid()))
      and s.read_at is null
  ) end;
$$;

create or replace function public.mark_system_mail_read_v1(p_mail_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode='28000'; end if;
  if not exists(
    select 1 from public.system_mail m
    where m.id = p_mail_id and m.starts_at <= now() and (m.expires_at is null or m.expires_at > now())
      and (m.audience_type='all' or (m.audience_type='user' and m.target_user_id=v_uid))
  ) then return false; end if;

  insert into public.player_mail_state(user_id,mail_id,read_at)
  values(v_uid,p_mail_id,now())
  on conflict(user_id,mail_id) do update set read_at = coalesce(public.player_mail_state.read_at, excluded.read_at);
  return true;
end;
$$;

create or replace function public.claim_system_mail_v1(p_mail_id bigint)
returns table(ok boolean, reason text, rewards jsonb, farm_state jsonb, revision bigint)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_rewards jsonb;
  v_state jsonb;
  v_claimed timestamptz;
  v_key text;
  v_value jsonb;
  v_qty integer;
  v_current integer;
  v_coins integer;
  v_exp integer;
  v_level integer;
  v_need integer;
  v_revision bigint;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode='28000'; end if;
  if not exists(select 1 from auth.users u where u.id=v_uid and nullif(u.email,'') is not null) then
    return query select false,'member_required','{}'::jsonb,null::jsonb,null::bigint; return;
  end if;

  select m.rewards into v_rewards
  from public.system_mail m
  where m.id=p_mail_id and m.starts_at<=now() and (m.expires_at is null or m.expires_at>now())
    and (m.audience_type='all' or (m.audience_type='user' and m.target_user_id=v_uid))
  for share;
  if not found then return query select false,'mail_unavailable','{}'::jsonb,null::jsonb,null::bigint; return; end if;
  perform private.validate_mail_rewards(v_rewards);
  if v_rewards = '{}'::jsonb then return query select false,'no_attachments',v_rewards,null::jsonb,null::bigint; return; end if;

  insert into public.player_mail_state(user_id,mail_id,read_at,claimed_at)
  values(v_uid,p_mail_id,now(),null)
  on conflict(user_id,mail_id) do nothing;

  select s.claimed_at into v_claimed
  from public.player_mail_state s where s.user_id=v_uid and s.mail_id=p_mail_id
  for update;
  if v_claimed is not null then return query select false,'already_claimed',v_rewards,null::jsonb,null::bigint; return; end if;

  insert into public.farm_saves(user_id,state,client_updated_at)
  values(
    v_uid,
    jsonb_build_object(
      'version',1,'createdAt',floor(extract(epoch from now())*1000)::bigint,
      'coins',100,'level',1,'exp',0,'plots','[]'::jsonb,
      'seeds',jsonb_build_object('carrot',3,'wheat',2),'produce','{}'::jsonb,
      'supplies',jsonb_build_object('fertilizerLow',0,'fertilizerMid',0,'fertilizerHigh',0),
      'stats',jsonb_build_object('visit',1,'plant',0,'harvest',0,'sell',0,'friend',0,'blindBoxPlant',0,'steals',0,'maxCoins',100),
      'updatedAt',floor(extract(epoch from now())*1000)::bigint
    ),
    floor(extract(epoch from now())*1000)::bigint
  ) on conflict(user_id) do nothing;

  select fs.state into v_state from public.farm_saves fs where fs.user_id=v_uid for update;
  v_state := coalesce(v_state,'{}'::jsonb);

  v_coins := greatest(0,coalesce(nullif(v_state->>'coins','')::integer,0)) + greatest(0,coalesce((v_rewards->>'coins')::integer,0));
  v_state := jsonb_set(v_state,'{coins}',to_jsonb(v_coins),true);
  v_state := jsonb_set(v_state,'{stats}',coalesce(v_state->'stats','{}'::jsonb),true);
  v_current := greatest(v_coins,coalesce(nullif(v_state->'stats'->>'maxCoins','')::integer,0));
  v_state := jsonb_set(v_state,'{stats,maxCoins}',to_jsonb(v_current),true);

  v_state := jsonb_set(v_state,'{seeds}',coalesce(v_state->'seeds','{}'::jsonb),true);
  if v_rewards ? 'seeds' then
    for v_key,v_value in select key,value from jsonb_each(v_rewards->'seeds') loop
      v_qty := greatest(0,trim(both '"' from v_value::text)::integer);
      v_current := greatest(0,coalesce(nullif(v_state->'seeds'->>v_key,'')::integer,0));
      v_state := jsonb_set(v_state,array['seeds',v_key],to_jsonb(v_current+v_qty),true);
    end loop;
  end if;

  v_state := jsonb_set(v_state,'{supplies}',coalesce(v_state->'supplies','{}'::jsonb),true);
  if v_rewards ? 'supplies' then
    for v_key,v_value in select key,value from jsonb_each(v_rewards->'supplies') loop
      v_qty := greatest(0,trim(both '"' from v_value::text)::integer);
      v_current := greatest(0,coalesce(nullif(v_state->'supplies'->>v_key,'')::integer,0));
      v_state := jsonb_set(v_state,array['supplies',v_key],to_jsonb(v_current+v_qty),true);
    end loop;
  end if;

  v_level := greatest(1,coalesce(nullif(v_state->>'level','')::integer,1));
  v_exp := greatest(0,coalesce(nullif(v_state->>'exp','')::integer,0)) + greatest(0,coalesce((v_rewards->>'exp')::integer,0));
  loop
    v_need := private.farm_exp_need(v_level);
    exit when v_exp < v_need;
    v_exp := v_exp - v_need;
    v_level := v_level + 1;
  end loop;
  v_state := jsonb_set(v_state,'{level}',to_jsonb(v_level),true);
  v_state := jsonb_set(v_state,'{exp}',to_jsonb(v_exp),true);
  v_state := jsonb_set(v_state,'{updatedAt}',to_jsonb(floor(extract(epoch from now())*1000)::bigint),true);

  update public.farm_saves fs
     set state=v_state, client_updated_at=floor(extract(epoch from now())*1000)::bigint, updated_at=now()
   where fs.user_id=v_uid
   returning fs.revision into v_revision;

  update public.player_mail_state
     set read_at=coalesce(read_at,now()), claimed_at=now()
   where user_id=v_uid and mail_id=p_mail_id;

  return query select true,'claimed',v_rewards,v_state,v_revision;
end;
$$;

create or replace function public.gm_send_system_mail_v1(
  p_title text,
  p_body text default '',
  p_mail_type text default 'announcement',
  p_audience_type text default 'all',
  p_target_user_id uuid default null,
  p_rewards jsonb default '{}'::jsonb,
  p_starts_at timestamptz default now(),
  p_expires_at timestamptz default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_id bigint;
begin
  if v_uid is null or not private.is_stellar_gm(v_uid) then raise exception 'gm_forbidden' using errcode='42501'; end if;
  if char_length(trim(coalesce(p_title,''))) < 1 or char_length(trim(p_title)) > 120 then raise exception 'invalid_title'; end if;
  if char_length(coalesce(p_body,'')) > 6000 then raise exception 'body_too_long'; end if;
  if p_mail_type not in ('announcement','reward') then raise exception 'invalid_mail_type'; end if;
  if p_audience_type not in ('all','user') then raise exception 'invalid_audience_type'; end if;
  if p_audience_type='all' then p_target_user_id := null; end if;
  if p_audience_type='user' and (p_target_user_id is null or not exists(select 1 from auth.users u where u.id=p_target_user_id)) then raise exception 'invalid_target_user'; end if;
  if p_expires_at is not null and p_expires_at <= coalesce(p_starts_at,now()) then raise exception 'invalid_expiry'; end if;
  perform private.validate_mail_rewards(coalesce(p_rewards,'{}'::jsonb));

  insert into public.system_mail(title,body,mail_type,audience_type,target_user_id,rewards,starts_at,expires_at,created_by)
  values(trim(p_title),coalesce(p_body,''),p_mail_type,p_audience_type,p_target_user_id,coalesce(p_rewards,'{}'::jsonb),coalesce(p_starts_at,now()),p_expires_at,v_uid)
  returning id into v_id;

  insert into public.gm_audit_log(gm_user_id,action,subject_id,detail)
  values(v_uid,'send_system_mail',v_id::text,jsonb_build_object('title',trim(p_title),'mail_type',p_mail_type,'audience_type',p_audience_type,'target_user_id',p_target_user_id,'rewards',coalesce(p_rewards,'{}'::jsonb)));
  return v_id;
end;
$$;

create or replace function public.gm_list_system_mail_v1(p_limit integer default 30)
returns table(
  id bigint,title text,mail_type text,audience_type text,target_user_id uuid,rewards jsonb,
  starts_at timestamptz,expires_at timestamptz,created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null or not private.is_stellar_gm(v_uid) then raise exception 'gm_forbidden' using errcode='42501'; end if;
  return query select m.id,m.title,m.mail_type,m.audience_type,m.target_user_id,m.rewards,m.starts_at,m.expires_at,m.created_at
    from public.system_mail m order by m.created_at desc,m.id desc limit least(greatest(coalesce(p_limit,30),1),100);
end;
$$;

revoke all on function private.is_stellar_gm(uuid) from public,anon,authenticated;
revoke all on function private.farm_exp_need(integer) from public,anon,authenticated;
revoke all on function private.validate_mail_rewards(jsonb) from public,anon,authenticated;

revoke all on function public.is_gm_v1() from public,anon;
revoke all on function public.get_mailbox_v1(integer) from public,anon;
revoke all on function public.get_mailbox_unread_v1() from public,anon;
revoke all on function public.mark_system_mail_read_v1(bigint) from public,anon;
revoke all on function public.claim_system_mail_v1(bigint) from public,anon;
revoke all on function public.gm_send_system_mail_v1(text,text,text,text,uuid,jsonb,timestamptz,timestamptz) from public,anon;
revoke all on function public.gm_list_system_mail_v1(integer) from public,anon;

grant execute on function public.is_gm_v1() to authenticated;
grant execute on function public.get_mailbox_v1(integer) to authenticated;
grant execute on function public.get_mailbox_unread_v1() to authenticated;
grant execute on function public.mark_system_mail_read_v1(bigint) to authenticated;
grant execute on function public.claim_system_mail_v1(bigint) to authenticated;
grant execute on function public.gm_send_system_mail_v1(text,text,text,text,uuid,jsonb,timestamptz,timestamptz) to authenticated;
grant execute on function public.gm_list_system_mail_v1(integer) to authenticated;

commit;
